### ISSUE TITLE
Managing the images in team section

### ISSUE THREAD

**Issue by scandindian** [fossasia/fossasia.org#171]
The second last image's size is not proper and the last image is not aligned with others.

![screenshot 16](https://user-images.githubusercontent.com/22588035/30480929-e25ac694-9a39-11e7-8936-28ed263f862a.png)

I think it should be aligned to the left.

**Comment by sagar-kalra** [comment]
problem of the last image persists in chrome, but is completely fine in firefox.

**Comment by mariobehling** [comment]
Vibhor's image is not in the correct size. Please adapt it to the correct size.

**Comment by vibhcool** [comment]
I have fixed the issue, please see https://github.com/fossasia/fossasia.org/pull/172
Nikhil Rayapralu's image is a bit smaller than the size.
an approach to prevent this issue can be to set fix size of height of images like the way width is set

**Comment by nzec** [comment]
This problem still persists.
![Image](https://i.imgur.com/ZWhiBlJ.png)

**Comment by mariobehling** [comment]
Seems solved.
